Get http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2Frc2hpIiwiaWF0IjoxNzMyNjg4ODMxfQ.GmsAN6S5gWiZUE1kirFHa37fN3l4Gst5q_QTdvb0M9A
### 
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"sakshi"
}


